server:
  port: 8180
  servlet:
      context-path: /storage-service
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true 
  application:
    name: storage-service
# cloud:
#   nacos:
#     discovery:
#       server-addr: 10.0.64.11:8848
# Logger Config
logging:
  level:
    com.mnuo.storage: debug
mybatis:
  mapperLocations: classpath:mapper/*.xml
#seata配置
seata:
  enabled: true
  application-id: seata-server
  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
  tx-service-group: tx_busi_group
  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
  service:
  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
    vgroup-mapping:
      tx_busi_group: default
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
    grouplist:
      default: 10.0.64.11:8091
#      disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      #这里的地址就是你的nacos的地址,可以更换为线上
      serverAddr: 10.0.64.11:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      max-retry: 20
      userName: 
      password: 
  registry:
    type: nacos
    nacos:
      application: seata-server
      #这里的地址就是你的nacos的地址,可以更换为线上
      server_addr: 10.0.64.11:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      max-retry: 20
      namespace:
      userName:
      password: