swagger:
  open: true
## 数据源配置
spring:
   datasource:
      # url: jdbc:mysql://localhost:3306/pink?characterEncoding=UTF-8&useUnicode=true&useSSL=false
      url: jdbc:mysql://localhost:3306/pink?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
# JPA配置
   jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect # mysql5.5版本使用 版本以上使用:org.hibernate.dialect.MySQLDialect
      show-sql: true   # 运行时输出jpa执行的sql语句
      hibernate:
         ddl-auto: update
   jackson:
       time-zone: GMT+8
   application:
      name: auth-service  
  
## 日志配置
logging:
  config: src/main/resources/logback.xml
  