server:
  port: 8088
swagger:
  open: true
spring:
   profiles:
     active: dev
   cloud:
      gateway:
         discovery:
            locator:
               lowerCaseServiceId: true
               enabled: true
           #   predicates:
           #      - name: Path
           #        args:
           #           pattern: "'/api/' + serviceId + '/**'"
           #   filters:
           #      - name: RewritePath
           #        args:
           #           regexp: "'/api/' + serviceId + '/(?<remaining>.*)'"
           #           replacement: "'/${remaining}'"
         routes: #配置路由路径
           - id: sso-service
             uri: lb://sso-service
             predicates:
                - Path=/api/sso/**
             filters:
                - StripPrefix=1
           - id: auth-service
             uri: lb://auth-service
             predicates:
                - Path=/api/auth/**
             filters:
                - StripPrefix=1
   redis:
      database: 0  
      host: 127.0.0.1
      # 服务器连接端口
      port: 6379
      # 服务器连接密码（默认为空）如果有变更为自己的
      password:
      # 连接池最大连接数（使用负值表示没有限制）
      pool:
         max-active: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1  
         # 连接池中的最大空闲连接
         max-idle: 8  
         # 连接池中的最小空闲连接
         min-idle: 0  
      # 连接超时时间（毫秒）
      timeout: 30000
## 日志配置
logging:
  config: src/main/resources/logback.xml
  
service:
   client:
      clientSecret: 123123
      clientId: client_1
      grantType:
         - password
         - refresh_token
   ignore:
      resources: 
         - /app/user
         - /oauth/*
         - /auth/user/login
         
  