server:
  port: 8182
  servlet:
      context-path: /toaccount-service
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-account?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123

  application:
    name: account-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.0.64.11:8848
# Logger Config
logging:
  level:
    com.mnuo.storage: debug
mybatis:
  mapperLocations: classpath:mapper/*.xml
#seata配置
seata:
  enabled: true
  application-id: seata-server
  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
  tx-service-group: tx_busi_group
  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
  service:
  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
    vgroup-mapping:
      tx_busi_group: default
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
    grouplist:
      default: bootstrap.yml:8091
#      disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      #这里的地址就是你的nacos的地址,可以更换为线上
      serverAddr: 10.0.64.11:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      max-retry: 20
      userName: 
      password: 
  registry:
    type: nacos
    nacos:
      application: seata-server
      #这里的地址就是你的nacos的地址,可以更换为线上
      server_addr: 10.0.64.11:8848
      #这里的名字就是registry.conf中 nacos的group名字
      group: SEATA_GROUP
      max-retry: 20
      namespace:
      userName: 
      password: 