server:
  port: 8080
  host: localhost
  servlet:
      context-path: /sso-service
swagger:
  open: true

## 日志配置
logging:
  config: src/main/resources/logback.xml
  
service:
   client:
      clientSecret: 123123
      clientId: client_1
      grantType:
         - password
         - refresh_token
   ignore:
      resources: 
         - /app/user
         - /oauth/*
         - /auth/user/login
         
  